const Annotation = require('./src/annotation');
const TraceId = require('./src/traceId');
const HttpHeaders = require('./src/httpHeaders');
const InetAddress = require('./src/InetAddress');
const option = require('./src/option');
const ZipkinTracer = require('./src/ZipkinTracer');
const consoleTracer = require('./src/consoleTracer');
const trace = require('./src/trace');
const serializeSpan = require('./src/serializeSpan');

module.exports.trace = trace;
module.exports.TraceId = TraceId;
module.exports.option = option;
module.exports.Annotation = Annotation;
module.exports.InetAddress = InetAddress;
module.exports.HttpHeaders = HttpHeaders;
module.exports.ZipkinTracer = ZipkinTracer;
module.exports.consoleTracer = consoleTracer;
module.exports.serializeSpan = serializeSpan;
